"""Fixed UPSC CSE syllabus taxonomy (GS papers -> subjects -> nodes).

The model must pick `subject` and `node` keys from this tree; anything else is
rejected by validation. Keys are stable and stored in the DB; labels are for UI.
Keep this file in sync with Satya/lib/upscSyllabus.ts (generated by
`python syllabus.py --ts > ../Satya/lib/upscSyllabus.ts`).
"""
import json
import sys

# subject_key: (paper, label, {node_key: label})
SYLLABUS = {
    # ---------------- GS1 ----------------
    "history_culture": ("GS1", "History & Culture", {
        "art_culture": "Art, architecture & culture",
        "ancient_medieval": "Ancient & medieval India",
        "modern_freedom": "Modern India & freedom struggle",
        "post_independence": "Post-independence consolidation",
        "world_history": "World history",
        "heritage": "Heritage sites, UNESCO & GI tags",
    }),
    "society": ("GS1", "Indian Society", {
        "women": "Women & gender issues",
        "population": "Population, demography & migration",
        "urbanisation": "Urbanisation",
        "communalism_secularism": "Communalism, regionalism & secularism",
        "diversity": "Social diversity, caste & tribes",
        "globalisation_society": "Globalisation & society",
    }),
    "geography": ("GS1", "Geography", {
        "physical": "Physical geography (landforms, oceans, climate)",
        "phenomena": "Geophysical phenomena (earthquakes, cyclones, volcanoes)",
        "resources": "Distribution of natural resources",
        "industry_location": "Location of industries",
        "places_in_news": "Places in news / mapping",
    }),
    # ---------------- GS2 ----------------
    "polity": ("GS2", "Polity & Constitution", {
        "constitution": "Constitution, amendments & basic structure",
        "fundamental_rights": "Fundamental rights, DPSP & duties",
        "parliament": "Parliament & state legislatures",
        "executive": "Executive (President, PM, Governor, CM)",
        "judiciary": "Judiciary & landmark judgments",
        "federalism": "Federalism & Centre-State relations",
        "elections": "Elections, ECI & electoral reforms",
        "constitutional_bodies": "Constitutional bodies (CAG, UPSC, FC, NCSC...)",
        "statutory_bodies": "Statutory, regulatory & quasi-judicial bodies",
        "local_government": "Panchayati Raj & urban local bodies",
    }),
    "governance": ("GS2", "Governance", {
        "schemes": "Government policies & schemes",
        "transparency": "Transparency, accountability & RTI",
        "egovernance": "e-Governance & citizen services",
        "civil_services": "Role of civil services",
        "civil_society": "NGOs, SHGs & civil society",
        "legislation": "Bills, Acts & ordinances",
    }),
    "social_justice": ("GS2", "Social Justice", {
        "vulnerable_sections": "Vulnerable sections (SC/ST, minorities, disabled, elderly, children)",
        "health": "Health policy & public health",
        "education": "Education policy",
        "poverty_hunger": "Poverty, hunger & nutrition",
        "human_resources": "Human resources & skilling",
    }),
    "ir": ("GS2", "International Relations", {
        "neighbourhood": "India & neighbourhood",
        "bilateral": "India's bilateral relations",
        "groupings": "Regional & global groupings (QUAD, BRICS, SCO, G20...)",
        "institutions": "International institutions & agencies (UN, WTO, IMF...)",
        "global_impact_on_india": "Policies of other countries affecting India",
        "diaspora": "Indian diaspora",
    }),
    # ---------------- GS3 ----------------
    "economy": ("GS3", "Economy", {
        "growth_indicators": "Growth, inflation & macro indicators",
        "monetary_banking": "Monetary policy, RBI & banking",
        "fiscal_budget": "Fiscal policy, budget & taxation (GST)",
        "external_trade": "External sector, trade & FDI",
        "industry_investment": "Industry, investment & MSMEs",
        "employment_inclusion": "Employment & inclusive growth",
        "infrastructure": "Infrastructure (energy, ports, roads, railways)",
        "capital_markets": "Capital markets & SEBI",
    }),
    "agriculture": ("GS3", "Agriculture", {
        "cropping_irrigation": "Cropping patterns & irrigation",
        "msp_procurement": "MSP, procurement, PDS & food security",
        "agri_subsidies": "Farm subsidies & support",
        "food_processing": "Food processing & supply chain",
        "land_reforms": "Land reforms",
        "allied": "Animal husbandry, fisheries & allied",
    }),
    "science_tech": ("GS3", "Science & Technology", {
        "space": "Space technology (ISRO, missions)",
        "defence_tech": "Defence technology",
        "biotech_health": "Biotechnology & health research",
        "it_ai": "IT, AI, semiconductors & computing",
        "energy_nuclear": "Nuclear & new energy technology",
        "ipr": "Intellectual property rights",
    }),
    "environment": ("GS3", "Environment & Ecology", {
        "biodiversity": "Biodiversity & conservation",
        "species_protected_areas": "Species, protected areas & wetlands",
        "pollution": "Pollution (air, water, plastic)",
        "climate_change": "Climate change & international agreements",
        "env_laws_eia": "Environmental laws, EIA & institutions",
    }),
    "disaster": ("GS3", "Disaster Management", {
        "natural_disasters": "Natural disasters & response",
        "dm_framework": "Disaster management framework (NDMA, SDRF)",
    }),
    "security": ("GS3", "Internal Security", {
        "lwe": "Left-wing extremism",
        "terrorism_insurgency": "Terrorism & insurgency (J&K, North-East)",
        "border_management": "Border management",
        "cyber": "Cyber security",
        "money_laundering": "Money laundering & organised crime",
        "security_forces": "Security forces & agencies",
    }),
    # ---------------- GS4 ----------------
    "ethics": ("GS4", "Ethics & Integrity", {
        "public_admin_ethics": "Ethics in public administration",
        "probity_corruption": "Probity, corruption & integrity",
        "case_study": "Ethical dilemma / case-study material",
        "tech_business_ethics": "Ethics in technology & business",
    }),
}

PAPERS = ["GS1", "GS2", "GS3", "GS4"]
EXAM_TYPES = ["prelims", "mains", "both"]


def paper_of(subject: str) -> str:
    return SYLLABUS[subject][0]


def is_valid(subject: str, node: str) -> bool:
    return subject in SYLLABUS and node in SYLLABUS[subject][2]


def prompt_tree() -> str:
    """Compact text rendering for the LLM prompt."""
    out = []
    for skey, (paper, label, nodes) in SYLLABUS.items():
        out.append(f"{paper} | subject={skey} ({label}): " + ", ".join(nodes))
    return "\n".join(out)


def to_ts() -> str:
    data = {k: {"paper": p, "label": l, "nodes": n} for k, (p, l, n) in SYLLABUS.items()}
    return ("// AUTO-GENERATED from satya-upsc-service/syllabus.py — do not edit by hand.\n"
            "export type UpscSubject = { paper: 'GS1' | 'GS2' | 'GS3' | 'GS4'; label: string; nodes: Record<string, string> }\n"
            f"export const UPSC_SYLLABUS: Record<string, UpscSubject> = {json.dumps(data, indent=2, ensure_ascii=False)}\n")


if __name__ == "__main__":
    if "--ts" in sys.argv:
        print(to_ts(), end="")
    else:
        print(prompt_tree())
